<?php

return array(

    'list' => array(
        'Abjasia',
        'Acrotiri y Dhekelia',
        'Afganistán',
        'Albania',
        'Alemania',
        'Andorra',
        'Angola',
        'Anguila',
        'Antigua y Barbuda',
        'Arabia Saudita',
        'Argelia',
        'Argentina',
        'Armenia',
        'Aruba',
        'Australia',
        'Austria',
        'Azerbaiyán',
        'Bahamas',
        'Baréin',
        'Bangladés',
        'Barbados',
        'Bélgica',
        'Belice',
        'Benín',
        'Bermudas',
        'Bielorrusia',
        'Birmania',
        'Bolivia',
        'Bosnia y Herzegovina',
        'Botsuana',
        'Brasil',
        'Brunéi',
        'Bulgaria',
        'Burkina Faso',
        'Burundi',
        'Bután',
        'Cabo Verde',
        'Caimán, Islas',
        'Camboya',
        'Camerún',
        'Canadá',
        'Catar',
        'Centroafricana, República',
        'Chad',
        'Checa, República',
        'Chile',
        'China',
        'Chipre',
        'Chipre del Norte',
        'Cocos, Islas',
        'Colombia',
        'Comoras',
        'Congo, República del',
        'Congo, República Democrática del',
        'Cook, Islas',
        'Corea del Norte',
        'Corea del Sur',
        'Costa de Marfil',
        'Costa Rica',
        'Croacia',
        'Cuba',
        'Curazao',
        'Dinamarca',
        'Dominica',
        'Dominicana, República',
        'Ecuador',
        'Egipto',
        'El Salvador',
        'Emiratos Árabes Unidos',
        'Eritrea',
        'Eslovaquia',
        'Eslovenia',
        'España',
        'Estados Unidos',
        'Estonia',
        'Etiopía',
        'Feroe, Islas',
        'Filipinas',
        'Finlandia',
        'Fiyi',
        'Francia',
        'Gabón',
        'Gambia',
        'Georgia',
        'Ghana',
        'Gibraltar',
        'Granada',
        'Grecia',
        'Groenlandia',
        'Guam',
        'Guatemala',
        'Guernsey',
        'Guinea',
        'Guinea-Bisáu',
        'Guinea Ecuatorial',
        'Guyana',
        'Haití',
        'Honduras',
        'Hong Kong',
        'Hungría',
        'India',
        'Indonesia',
        'Irak',
        'Irán',
        'Irlanda',
        'Islandia',
        'Israel',
        'Italia',
        'Jamaica',
        'Japón',
        'Jersey',
        'Jordania',
        'Kazajistán',
        'Kenia',
        'Kirguistán',
        'Kiribati',
        'Kosovo',
        'Kuwait',
        'Laos',
        'Lesoto',
        'Letonia',
        'Líbano',
        'Liberia',
        'Libia',
        'Liechtenstein',
        'Lituania',
        'Luxemburgo',
        'Macao',
        'Macedonia',
        'Madagascar',
        'Malasia',
        'Malaui',
        'Maldivas',
        'Malí',
        'Malta',
        'Man, Isla de',
        'Marianas del Norte, Islas',
        'Marruecos',
        'Marshall, Islas',
        'Mauricio',
        'Mauritania',
        'México',
        'Micronesia',
        'Moldavia',
        'Mónaco',
        'Mongolia',
        'Montenegro',
        'Montserrat',
        'Mozambique',
        'Nagorno Karabaj',
        'Namibia',
        'Nauru',
        'Navidad, Isla de',
        'Nepal',
        'Nicaragua',
        'Níger',
        'Nigeria',
        'Niue',
        'Norfolk, Isla',
        'Noruega',
        'Nueva Caledonia',
        'Nueva Rusia',
        'Nueva Zelanda',
        'Omán',
        'Osetia del Sur',
        'Países Bajos',
        'Pakistán',
        'Palaos',
        'Palestina',
        'Panamá',
        'Papúa Nueva Guinea',
        'Paraguay',
        'Perú',
        'Pitcairn, Islas',
        'Polinesia Francesa',
        'Polonia',
        'Portugal',
        'Puerto Rico',
        'Reino Unido',
        'Ruanda',
        'Rumania',
        'Rusia',
        'Sahara Occidental',
        'Salomón, Islas',
        'Samoa',
        'Samoa Americana',
        'San Bartolomé',
        'San Cristóbal y Nieves',
        'San Marino',
        'San Martín',
        'Sint Maarten',
        'San Pedro y Miquelón',
        'San Vicente y las Granadinas',
        'Santa Elena, Ascensión y Tristán de Acuña',
        'Santa Lucía',
        'Santo Tomé y Príncipe',
        'Senegal',
        'Serbia',
        'Seychelles',
        'Sierra Leona',
        'Singapur',
        'Siria',
        'Somalia',
        'Somalilandia',
        'Sri Lanka',
        'Suazilandia',
        'Sudáfrica',
        'Sudán',
        'Sudán del Sur',
        'Suecia',
        'Suiza',
        'Surinam',
        'Svalbard',
        'Tailandia',
        'Taiwán',
        'Tanzania',
        'Tayikistán',
        'Timor Oriental',
        'Togo',
        'Tokelau',
        'Tonga',
        'Transnistria',
        'Trinidad y Tobago',
        'Túnez',
        'Turcas y Caicos, Islas',
        'Turkmenistán',
        'Turquía',
        'Tuvalu',
        'Ucrania',
        'Uganda',
        'Uruguay',
        'Uzbekistán',
        'Vanuatu',
        'Vaticano, Ciudad del',
        'Venezuela',
        'Vietnam',
        'Vírgenes Británicas, Islas',
        'Vírgenes de los Estados Unidos, Islas',
        'Wallis y Futuna',
        'Yemen',
        'Yibuti',
        'Zambia',
        'Zimbabue',
    ),

);